### ISSUE TITLE
Issue with Windows 10 Scaling Settings. Unable to override

### ISSUE THREAD

**Issue by trebory6** [rohatsu/ShaderGlass#14]
First off, thank you for this software, it's like exactly what I'm looking for for my retro media center. 

However, I've run into an issue. It seems that whenever I open this, it doesn't display the full screen, only the top left corner very zoomed in. 

This is probably because I have Scaling enabled on my 4K TV's desktop due to how small the text would be otherwise. 

I tried going into the .exe's properties > Compatibility > Change High DPI Settings > High DPI Override, but no matter what I select, the program opens up zoomed in. 

When I completely disabled Scaling in windows, and tried again, it worked 100%, however it just makes the experience unusable due to being unable to read anything from across the room. 

Is there any fix for this incoming? This is like the program I've been looking for for years.

**Comment by trebory6** [comment]
So for others having this issue, I was able to fix this by right clicking the exe, Troubleshoot Compatibility > Troubleshoot Program > "This program doesn't display correctly" > "Program does not display properly when large scale font settings are selected" > Test and follow the prompts. 

I'll leave this open since it does seem to be a bug with scaling and the above is a workaround. Feel free to close this, @rohatsu  if you feel this is a solid solution! Thanks again!

**Comment by rohatsu** [comment]
Thanks for flagging and the workaround, I'll try to get it fixed properly though. Could you post screenshot of your Windows display settings (i.e. the place that shows the DPI scaling)?

**Comment by rohatsu** [comment]
Please try 0.5-beta2, it should now work on scaled displays. There might still be issues on multiple monitors, in which case it's best to select just one input rather than "All Displays".

https://github.com/rohatsu/ShaderGlass/releases/tag/v0.5-beta2
