### ISSUE TITLE
Fullscreen Issues

### ISSUE THREAD

**Issue by ruskerusker** [rohatsu/ShaderGlass#2]
Great software, but I'm facing some issues. When going fullscreen on Glass mode the window below basically becomes irresponsive, as controls are applied by default to the active window (in this case, ShaderGlass window). Then, if I activate the window below, fullscreen mode switches to windowed. I guess it is a standard Windows behavior. That is somewhat problematic, as sometimes Clone mode leaves window edges intact and you can't do anything with it, while in Glass mode you can first force-resize emulator window to fullscreen with borders left out. 
I think this can be fixed by adding window staying on top option combined with borderless window mode available with custom window resolution settings. What do you think?

**Comment by ruskerusker** [comment]
Managed to solve this using Fullscreenizer. It pins the shader window on top and removes borders, which allows you to control the window underneath. Still would be great if this could be implemented without it, though.

**Comment by siriusinko** [comment]
This is not an option, Fullscreenizer spoils the aspect ratio. I would still like a normal full-screen mode.

**Comment by ruskerusker** [comment]
I'm certain it does not spoil anything. Works perfectly for me.

**Comment by rohatsu** [comment]
Many thanks for the feedback, yes I want to make fullscreen work - will take a look this week. If you're using any other emulators than ones I listed please let me know so I can test those as well.

**Comment by siriusinko** [comment]
> Many thanks for the feedback, yes I want to make fullscreen work - will take a look this week. If you're using any other emulators than ones I listed please let me know so I can test those as well.

Why only emulators? I would like to use it in individual games, for example, indie games

**Comment by ruskerusker** [comment]
It doesn't actually matter, it's not like it's software-dependent. Can be used with anything.

**Comment by rohatsu** [comment]
Could you try the attached beta version, press Ctrl+Shift+G to flip between normal and borderless fullscreen modes. I've quickly tested with ScummVM and AGS and it looks good but it's still a bit wonky in other modes. I want to make Window Clone mode work here (by means of auto-resize) so that it's possible to play in fullscreen without the annoying yellow outline (it's sort of possible now if you can set scaling so that it ends up covering the whole screen, set window to click-through and go borderless...)
[ShaderGlass-beta.zip](https://github.com/rohatsu/ShaderGlass/files/6035819/ShaderGlass-beta.zip)

**Comment by ruskerusker** [comment]
Sure, I'll give it a try when I get home. Thanks a bunch.

**Comment by ruskerusker** [comment]
Yeah, works just fine, great. No yellow borders as well. The only thing it goes fullscreen on the main display, so I then put it on the second one with ShiftWindow. Not a problem though, because I use it anyway to resize the emulator as well to remove borders.

**Comment by ruskerusker** [comment]
By the way, works pretty well with OBS in Glass mode, here's a video capture. That's exactly what i see on my other monitor as well.
[https://youtu.be/XsHuy4ZuEXQ](url)

**Comment by rohatsu** [comment]
Great, thanks for testing. It should have fullscreened to the monitor it's currently on so it's a bug and I'll take a look at it.

**Comment by rohatsu** [comment]
Released in v0.3
