### ISSUE TITLE
Windows 10 Version 1909 CTD

### ISSUE THREAD

**Issue by torridgristle** [rohatsu/ShaderGlass#3]
The requirements say version 2004, and partially 1903, but in case Win10 version 1909 was intended to be functional as well:

When running ShaderGlass the program's UI opens, it's unresponsive, and it closes without giving any errors. If I try to run it from command line to see if there's an output for --help, it'll open and be unresponsive, but it won't close. It'll just stay open.

Here's a crash dump, a crash report, and Dependency Walker output.
[Report_and_DMP.zip](https://github.com/rohatsu/ShaderGlass/files/6173913/Report_and_DMP.zip)
[DependencyWalker_Output.zip](https://github.com/rohatsu/ShaderGlass/files/6173915/DependencyWalker_Output.zip)

**Comment by rohatsu** [comment]
Thanks for checking out the app. I've fixed 1909 crash in the latest hotfix, please give it a shot. On 1909 you won't get the headline Desktop Glass mode as it requires newer Windows Capture API. Desktop Clone and Window modes will work and depending on your emulator/input should do the trick though. One last bit that's not supported by 1909 is hiding the mouse cursor from capture.

**Comment by torridgristle** [comment]
It's not crashing in this latest version, but there's two things that I'm not sure are intended.
![Clipboard01](https://user-images.githubusercontent.com/23273466/111892201-a25a6200-89cf-11eb-8520-4140c9ae0661.png)
There's a border around my desktop, and my captured desktop doesn't fit within the window. I would've expected some kind of scale to fit.

**Comment by rohatsu** [comment]
Great, the yellow border is unfortunately forced by Windows Capture API (for "security" reasons) and nested desktop is just how Desktop Clone mode is (as opposed to Glass which doesn't work on 1909), there is no scale to fit - this mode is really only useful if you have multiple displays. For best results on 1909 change Input to a Window (your game or emulator) and then flip between Output Glass (if you need mouse pass-through, position ShaderGlass over your game window) and Clone modes (f your emulator captures mouse you can have emulator in the background and play with ShaderGlass on top).

**Comment by rohatsu** [comment]
Fixed in 0.3.1
