### ISSUE TITLE
Windows 10 Enterprise Version 1809 cant install.

### ISSUE THREAD

**Issue by Axel-Moore** [rohatsu/ShaderGlass#5]
Hi im using Windows 10 LTSC 1809 and when i try to install Shader Glass it says it reqs Windows 10 1903. Any way to fix that? Thank you for your fantastic work.

**Comment by rohatsu** [comment]
Thanks for the feedback, unfortunately it won't be possible - ShaderGlass relies on the new Windows Capture API introduced in 1903 and enhanced in 2004 for full functionality, its ability to do transparent capture is how I got the idea for the app in the first place. Even if I added legacy capture APIs it wouldn't ever work as intended on older versions of Windows, hopefully it will work on the new LTSC coming later this year.
