### ISSUE TITLE
duel monitor issues

### ISSUE THREAD

**Issue by squidud** [rohatsu/ShaderGlass#7]
I have an issue where in glass mode, everything is shifted over because I have 2 monitors. I don't really need or want to use the shader on both, so maybe add something where you select which monitor you want to use the shader on.

**Comment by rohatsu** [comment]
Thanks for flagging this, I am working on monitor selection however the current version should work fine on dual monitors. Could you post a screenshot of your Windows Display Setting showing screen arrangement, please? Is there anything special about your setup (dual GPU or...?)

**Comment by squidud** [comment]
Here is the screenshot of my display settings: https://imgur.com/a/EfRO5cq
I think my setup is fairly normal. I am using 1 GPU (RTX 2060 super) and 2 displays (1440p and 1080p) 
Perhaps it is because my secondary screen is in portrait orientation? 
I really appreciate you helping me out here.
(also I tried to screenshot the actual application as well, but it's invisible in screenshots)

**Comment by rohatsu** [comment]
Unfortunately I'm not able to replicate this issue even if I arrange screens same way and I actually have identical GPU. Can you try the latest beta where you can choose individual desktops and see how that works, please?
https://github.com/rohatsu/ShaderGlass/releases/download/v0.4-beta/ShaderGlass-0.4-beta-win-x64.zip

**Comment by squidud** [comment]
Ok so I tried it out and it sort of solves the issue. Everything is still shifted in glass mode when both displays are selected. When I only one display it works perfectly. If you would like, I can take a picture of my screen with my phone so that you could see the bug.

**Comment by rohatsu** [comment]
I think I found the problem, your primary monitor I suspect is the right one so left screen has negative coordinates which I have to account for. Please try the latest beta:
https://github.com/rohatsu/ShaderGlass/releases/download/0.4-beta2/ShaderGlass-0.4-beta2-win-x64.zip

**Comment by rohatsu** [comment]
No problem, thanks for helping me improve the app!

Fixed in v0.4
